
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const About = lazy(() => import("./pages/About.tsx"));
const Admin = lazy(() => import("./pages/Admin.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const Contact = lazy(() => import("./pages/Contact.tsx"));
const Projects = lazy(() => import("./pages/Projects.tsx"));
const SetupGuide = lazy(() => import("./pages/SetupGuide.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/about", element: <About />},
	{ path: "/admin", element: <Admin />},
	{ path: "/", element: <App />},
	{ path: "/contact", element: <Contact />},
	{ path: "/projects", element: <Projects />},
	{ path: "/setup-guide", element: <SetupGuide />},
	{ path: "/setupguide", element: <SetupGuide />},

];
